name: Unprivileged CI

on: 
  pull_request:
    branches:
    - master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/escalator-action@v0.0.1
        with:
          url: https://escalatoraction.azurewebsites.net/
